spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/books}
    username: ${DATABASE_USERNAME:julia}
    password: ${DATABASE_PASSWORD:}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/dbchangelog.postgresql.sql
  redis:
    host: localhost
    port: 6379
books:
  origin:
    user: http://localhost:4200
    admin: http://localhost:4201
logging:
  file:
    path: ${BOOKS_LOGS_PATH:/Users/julia/logs/books}
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE

  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
