spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/books}
    username: ${DATABASE_USERNAME:julia}
    password: ${DATABASE_PASSWORD:}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/dbchangelog.postgresql.sql
  mail:
    protocol: smtps
    host: ${BOOKS_MAIL_HOST}
    username: ${BOOKS_MAIL_USERNAME}
    password: ${BOOKS_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    template:
      exchange: books-exchange
books:
  origin:
    user: http://localhost:4200
    admin: http://localhost:4201
  email:
    from: ${BOOKS_MAIL_FROM}
  bot:
    url: https://test-quotes-bot.herokuapp.com
    username: ${BOT_USERNAME}
    password: ${BOT_PASSWORD}
logging:
  file:
    path: ${BOOKS_LOGS_PATH:/Users/julia/logs/books}
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE

  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
